### ISSUE TITLE
Nodejs for Beginners | How to get involve?

### ISSUE THREAD

**Issue by cukejianya** [mikeal/ama#10]
I know you probably answered this question a million times before. But since this is an "ama"... What are some projects, online communities to join, or things that a beginner programmer can do to contribute to the nodejs community or level up their nodejs? Also, I'm major fan of NodeUp. Currently on episode 40.

**Comment by mikeal** [comment]
I would think more about what you're comfortable contributing to (websites, events, low-level C++) and then apply that to a new community like Node.js. Then you get to feel comfortable with the technical part as you acclimate to the community. Once you are comfortable in the community you can take on technical tasks you're less familiar with.
