### ISSUE TITLE
What's the most important advice you would give a new open source project?

### ISSUE THREAD

**Issue by srl295** [mikeal/ama#12]
People are important… but committers and maintainers are people too. What advice would you give a project that's just published 1.0 somewhere?

**Comment by mikeal** [comment]
In a lot of ways, I just don't live in the same world as brand new contributors do. I think that most people are fighting a lot more for attention, while I intentionally hide projects until I'm ready to speak to them.

That said, here's a list of things I do very different in new projects that I wish I had done in old ones:

* No project gets released without 100% test coverage.
* No project gets released without fully automated releases w/ semantic-release (which obviously require maintaining 100% coverage from above).

I just don't have the capability anymore to handle in-bound requests for PRs and releases without this level of testing and automation.
